version: "3"
services:

  jupyter:
    build:
      context: ./docker
    ports:
      - "8888:8888"
    links:
      - postgis
    volumes:
          - "./notebooks:/notebooks" 
          - "./data:/data"

  postgis:
    image: postgis/postgis
    restart: always
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: bcn_traffic
      POSTGRES_USER: bcn
      POSTGRES_PASSWORD: bcn
      
